### ISSUE TITLE
Forseti scanner run does not work

### ISSUE THREAD

**Issue by hshin-g** [forseti-security/helm-charts#10]
SSH-ing into the `forseti-server` container in the `forseti-server-xxx` pod (`kubectl exec -it <POD> -c <CONTAINER> bash`),`forseti scanner run` does not work. 

It does not look like the scanner is working for `forseti-orchestrator` either, since violations do not seem to have been generated whenever the cron job runs.

The error is below:

```forseti@forseti-server-584648d8fc-4rzsn:/$ forseti scanner run
{
  "serverMessage": "Error occurred during the scanning process."
}
forseti@forseti-server-584648d8fc-4rzsn:/$ forseti scanner
Traceback (most recent call last):
  File "/home/forseti/.local/bin/forseti", line 11, in <module>
    load_entry_point('forseti-security==2.18.0', 'console_scripts', 'forseti')()
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/stubs.py", line 34, in RunForsetiCli
    forseti_cli.main()
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/services/cli.py", line 1175, in main
    services[config.service](client, config, output, config_env)
  File "/home/forseti/.local/lib/python3.6/site-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/services/cli.py", line 690, in run_scanner
    scanner_name = config.scanner
AttributeError: 'Namespace' object has no attribute 'scanner'

**Comment by kevensen** [comment]
I think we would need to set the PYTHONPATH variable in the container.  This is easy enough to do, but I am not sure we want to.  Nominally, this is not how a user would interact with the server.  I'll leave this open to discussion.

**Comment by kevensen** [comment]
I think this has been OBE.  @hshin-g let me know if you agree.

* The intended behavior is that no user should expect to `kubectl exec` into the server container
* IIRC we figured out the problem with the orchestrator

**Comment by kevensen** [comment]
Closing for now.
